drop table if exists member CASCADE;
-- generated by default as identity : 시퀀스 같은거임
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
